blank_issues_enabled: false
contact_links:
    - name: File an issue
      url: https://github.com/gemini-testing/testplane/issues
      about: We track issues in the gemini-testing/testplane repository
