name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        strategy:
            matrix:
                # TODO: return windows-latest
                os: [ubuntu-latest, macos-latest]
                node-version: [20.x]
                include:
                    - os: ubuntu-latest
                      node-version: 18.x
                vscodeVersion:
                    - stable

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build
            - name: Run Tests
              uses: coactions/setup-xvfb@v1
              with:
                  run: npm test
              env:
                  RUN_IN_CI: true
                  VSCODE_VERSION: ${{ matrix.vscodeVersion }}
            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: screens-on-fail
                  path: tests/e2e/screens-on-fail
